### ISSUE TITLE
Migrate from Hugo to Astro

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/my-articles#2]
I think that moving to [Astro](https://astro.build/) will bring some advantages. Using [React](https://docs.astro.build/en/guides/integrations-guide/react/) and [Tailwind](https://docs.astro.build/en/guides/integrations-guide/tailwind/) is very convenient for me, in addition to the [content collections](https://docs.astro.build/en/guides/content-collections/) API itself that seems really simple

###### Tasks

- [x] Remove Hugo project and setup Astro [973ff85]
- [x] Create link tree page (`/`) [36dae82]
- [x] Create about me page (`/about`) [f919938]
- [x] Create projects page (`/projects`) [ea23023]
- [x] Create blog page (`/blog`) [ac4c216]
---

For the interface I have some references:

- [Datsfilipe website](https://datsfilipe.dev/)
- [Discord blog](https://discord.com/blog)
- [GitHub blog](https://github.blog/)
- [/blog Nicolas Solerieu](https://dribbble.com/shots/23563106--blog)
- [Framer Template: Blog](https://dribbble.com/shots/18432052-Framer-Template-Blog)
- [Typo theme](https://themes.gohugo.io/themes/typo/)
